### ISSUE TITLE
Migrating from List View to Recycler View

### ISSUE THREAD

**Issue by mishraaditya595** [mishraaditya595/ScanIt#11]
Listview is used in the home fragment to show all the scanned documents. Implementing the much-improved Recycler View can be done.

**Comment by codeDamon** [comment]
I want to work on this issue. Please assign this to me.

**Comment by mishraaditya595** [comment]
Ok assigning it to you.

**Comment by Riyanka18** [comment]
I want to work on this issue during the GirlScript Summer of Code

**Comment by MukulKolpe** [comment]
Hey, I am GSSOC'21 participant. I am interested to work on this project. Can you please assign this issue to me???

**Comment by MukulKolpe** [comment]
Okk... @codeDamon
