### ISSUE TITLE
Implementing a Settings/Info page

### ISSUE THREAD

**Issue by mishraaditya595** [mishraaditya595/ScanIt#12]
There is no fragment/activity to show the settings or about section for the app. It can contain a toggle for light/dark mode, the open-source licences, privacy policies and other similar things.

**Comment by codeDamon** [comment]
I want to work on this issue. Please assign this to me.

**Comment by mishraaditya595** [comment]
Ok assigning it to you.

**Comment by codeDamon** [comment]
I think this issue needs to be closed.
