### ISSUE TITLE
Implementing share as jpg/png feature

### ISSUE THREAD

**Issue by mishraaditya595** [mishraaditya595/ScanIt#14]
Currently, the scanned documents can be shared only in the form of a pdf. A feature to provide the user with an option to share the scanned document in the form of an image can be implemented.

**Comment by kunal299** [comment]
@mishraaditya595 Hey, I am a participant of GirlScript Summer of Code. I am interested in contributing to this issue when the GSSoc starts.

**Comment by mishraaditya595** [comment]
I have not received any notice from the organisers to start assigning issues. I will do it as soon as I get confirmation from their side. Glad to see your interest.

**Comment by kunal299** [comment]
@mishraaditya595 ya sure.

**Comment by mishraaditya595** [comment]
Hey @kunal299, you have already been assigned issue #15. Once that is completed, you can start working on others.

**Comment by kunal299** [comment]
@mishraaditya595 ok

**Comment by coderdada6** [comment]
Hey, I am a participant at GSSoc'21 , I am really interested to contribute to this issue can you assign me?

**Comment by rasikabakre** [comment]
As a participant of GSSoc' 21, I would really like to contribute to this issue! Could you assign it to me?

**Comment by amritakesh** [comment]
hello
i'm taking part in gssoc 2021. And i would like work on this issue, will you please assign this to me?

**Comment by mishraaditya595** [comment]
Hey guys, sorry for the delayed response. As there are multiple responses, I would like to give this opportunity to all of you to work around your solutions. Please reply back those who are interested.

**Comment by kunal299** [comment]
@mishraaditya595 Hey, I am interested in solving this issue. Please assign it to me. I will complete it and create a pr by tomorrow

**Comment by rahulsain** [comment]
> Hey guys, sorry for the delayed response. As there are multiple responses, I would like to give this opportunity to all of you to work around your solutions. Please reply back those who are interested.

Hey, could you please assign me this issue?

**Comment by mishraaditya595** [comment]
Hey @kunal299, you can start working on it.

**Comment by mishraaditya595** [comment]
Hello @gargijs, you can start working,

**Comment by rahulsain** [comment]
Can I work on this?
