### ISSUE TITLE
Creation of Issue Template

### ISSUE THREAD

**Issue by mishraaditya595** [mishraaditya595/ScanIt#18]
An issue template for the project can be created.

**Comment by Aarush-Goyal** [comment]
@mishraaditya595 can I work on it?

**Comment by mishraaditya595** [comment]
Sure, I am assigning the issue to you.  @Aarush-Goyal

**Comment by kanishkaa24** [comment]
I would love to work on it.

**Comment by mishraaditya595** [comment]
Hey @Aarush-Goyal, any updates?
