### ISSUE TITLE
Integrate Welcome and Greeting Bot 

### ISSUE THREAD

**Issue by akrish4** [mishraaditya595/ScanIt#21]
Hi @mishraaditya595 
I would like to contribute to this amazing project 
I can add a config file and integrate the bot so that whenever a new user opens a issue or pr , the bot will comment and greet the user with a proper message 

Let me know if you are interested

Kindly do assign me

**Comment by mishraaditya595** [comment]
Sounds good @akrish4. I am assigning the issue to you.

**Comment by akrish4** [comment]
Hi @mishraaditya595 
I have wworked on it , kindly do check and merge it 
#29 
Thank you
