### ISSUE TITLE
readme updation

### ISSUE THREAD

**Issue by Sloth-Panda** [mishraaditya595/ScanIt#23]
Readme can be updated by adding links to code of conduct , contributing file, and also including various open-source programs this project a part of, also emojis 

let me know if this needs to be done

**Comment by mishraaditya595** [comment]
Sounds good @Sloth-Panda. Assigning you this issue.

**Comment by Sloth-Panda** [comment]
plz add the dwoc" and a level" tag to it

**Comment by Sloth-Panda** [comment]
pr-> #26
