### ISSUE TITLE
Integrate Welcome bot

### ISSUE THREAD

**Issue by muthuannamalai12** [mishraaditya595/ScanIt#28]
Hello there,
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time as a part of DWOC. Please assign me this issue.
For reference, kindly check out: https://github.com/apps/welcome

THANK YOU

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign it to me

**Comment by mishraaditya595** [comment]
The project is not accepting any more bot requests for now.

If you want to contribute, you must have an eligible contribution. You will find things that you can work on under the issues tab.
