### ISSUE TITLE
Missing google-services.json file

### ISSUE THREAD

**Issue by codeDamon** [mishraaditya595/ScanIt#34]
**Description**
There should be a file named - "google-services.json" in the project to use firebase services. 
When running(installing) the project on android device an error arrives.(Refer screenshot)

Please @mishraaditya595 , add this file in the project.

**Working Environment**
Android Studio 4.1.2

**Screenshots**
![error_screenshot](https://user-images.githubusercontent.com/59572531/105698382-cd728900-5f2b-11eb-8dd6-0ee7f2aba09b.png)

**Comment by mishraaditya595** [comment]
I cannot add this file. That contains my api info. You have to create a firebase project for the app and get the google-services.json file from there.

**Comment by codeDamon** [comment]
Ok, I understand. Created google-services.json. Thanks.
