### ISSUE TITLE
Contributors table in readme.md file. 

### ISSUE THREAD

**Issue by Swastik1710** [mishraaditya595/ScanIt#39]
**Description**

I wanna add a Contributors table in the readme file which will keep updating automatically. 
Also, I'll be adding a separate line to showcase the project admin in the readme file. 

**Stack**

Project stack or language (eg. Frontend):

**Working Environment**

Operating System (eg Linux):

Browser (eg. Chrome):

Device (eg. Laptop or Phone):

**Screenshots**

Please add a screenshot if applicable

[Optional] **Additional Context**

**Comment by Swastik1710** [comment]
Kindly assign me this issue so that I can start working on this.

**Comment by anirudhsai20** [comment]
Hi @mishraaditya595 . Kindly assign me this issue under GSSOC.

**Comment by mishraaditya595** [comment]
This ain't a part of GSSOC
