### ISSUE TITLE
Json File missing 

### ISSUE THREAD

**Issue by Areeb-510** [mishraaditya595/ScanIt#44]
**Description**
The google-services.json file is missing in the project. Should we resolve this issue by using our firebase account for the same

Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it.

Project stack or language (eg. Frontend):
Android Java

**Comment by Rads1208** [comment]
google-services.json file is missing, it is not a bug. You will have to generate your own google-services.json file from the firebase console.

1. Go to - > https://console.firebase.google.com/
2. Now create a new project there and fill required fields such as app package name, app name, etc.
3. Now It will give you an option to download your google-services.json file.
4. after downloading the file place that inside the 'app' directory of your android project and you are good to go.

NOTE: You can find app package name inside the 'build.gradle' file which is present in the 'app' folder of your android project.

**Comment by mishraaditya595** [comment]
That should solve the issue. Thanks!

**Comment by Rads1208** [comment]
> That should solve the issue. Thanks!

@mishraaditya595 Welcome! I'm a participant of GSSoC
