### ISSUE TITLE
Readme Improvements

### ISSUE THREAD

**Issue by mishraaditya595** [mishraaditya595/ScanIt#46]
Updates to the readme in a positive way.

**Comment by ArshpreetS** [comment]
What kind of updates are you expecting?

**Comment by rahulsain** [comment]
Please assign me this issue and what kind of improvements do I have to make?

**Comment by mishraaditya595** [comment]
You can use your creativity for the ReadMe. If I like it, I will merge it. One thing that I have on the bucket list is adding the GSSOC tag at the end as the readme already has for DWOC. I am assigning the issue to both of you. Use all your creativity as you wish.

**Comment by rahulsain** [comment]
@mishraaditya595 Please check if you want any more improvements

**Comment by amritakesh** [comment]
hello
i'm taking part in gssoc 2021. And i would like work on this issue, will you please assign this to me?

**Comment by ArshpreetS** [comment]
#56 Please check and confirm my PR for this issue.

**Comment by shubhidua** [comment]
I would like to contribute to the above problem in java as I am a participant of GSSOC'21. Kindly assign this to me.

**Comment by mishraaditya595** [comment]
Hey, this issue has been closed.
