### ISSUE TITLE
Will like to add the contribution section in read me and update the tech stack used with the logo in readme 

### ISSUE THREAD

**Issue by rohank2502** [mishraaditya595/ScanIt#47]
I will like to add the contribution section at the end of read me this will keep updating automatically and also like to add the tech stack section with their logo this will make our read me file more attractive !! Will start to work on this issue as soon as I get assigned !!

**Comment by mishraaditya595** [comment]
Hey @rohank2502, glad to see your interest in ScanIt.The things you mentioned feels pretty unnecessary to me. There are a bunch of live issues. You can try to fix those or can reach out with some better ideas for improving the project.
