### ISSUE TITLE
update contributing.md

### ISSUE THREAD

**Issue by khareyash05** [mishraaditya595/ScanIt#48]
Hey! I would like to add the following in contributing.md
Add the following -

1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream
I would like to work on this as a part of GSSOC'21

**Comment by mishraaditya595** [comment]
Hey @khareyash05, glad to see your interest in ScanIt.The things you mentioned are just one web search away and feels pretty unnecessary to me. There are a bunch of live issues. You can try to fix those or can reach out with some better ideas for improving the project.
