### ISSUE TITLE
google-services-json error

### ISSUE THREAD

**Issue by iamsachin45** [mishraaditya595/ScanIt#52]
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  C:\Users\hp\AndroidStudioProjects\ScanIt\app\src\nullnull\debug\google-services.json
  C:\Users\hp\AndroidStudioProjects\ScanIt\app\src\debug\nullnull\google-services.json
  C:\Users\hp\AndroidStudioProjects\ScanIt\app\src\nullnull\google-services.json
  C:\Users\hp\AndroidStudioProjects\ScanIt\app\src\debug\google-services.json
  C:\Users\hp\AndroidStudioProjects\ScanIt\app\src\nullnullDebug\google-services.json
  C:\Users\hp\AndroidStudioProjects\ScanIt\app\google-services.json

**Comment by iamsachin45** [comment]
i have founded a solution using firebase.Is there any way to solve this using android stdio code?

**Comment by mishraaditya595** [comment]
the only way to solve it is that you need to integrate firebase with the project. Just open a new firebase project and download the JSON file from there and place that inside the 'app' directory of your android project and you are good to go.

**Comment by rahulsain** [comment]
> the only way to solve it is that you need to integrate firebase with the project. Just open a new firebase project and download the JSON file from there and place that inside the 'app' directory of your android project and you are good to go.

Do we also have to add google-services.json from our end too?
