### ISSUE TITLE
Problem in the OCR Fragment of the app

### ISSUE THREAD

**Issue by Priyanshu078** [mishraaditya595/ScanIt#53]
There is a typo in the OCR fragment
" Click on the '+' icon to start extracting texts "fromt" the images." 
It should be "from" in place of "fromt".

I want to work on this issue, Kindly assign it to me.
Here is the screenshot
![1603558656662](https://user-images.githubusercontent.com/66347715/111157380-d511ee00-85bc-11eb-8b0e-023171f939c7.png)

**Comment by Priyanshu078** [comment]
I want to work on this issue, kindly  assign it to me

**Comment by Priyanshu078** [comment]
I am a GSSOC participant

**Comment by mishraaditya595** [comment]
Fixed in upcoming versions!
