### ISSUE TITLE
Adding CONTRIBUTORS.md file

### ISSUE THREAD

**Issue by rajeshpanjiyar** [mishraaditya595/ScanIt#54]
**Hi,** I would like to add a contributors file to add the **name and GitHub handle** of respected contributors.
- I am a participant under GSSoC'21

**Comment by amritakesh** [comment]
hello
i'm taking part in gssoc 2021. And i would like work on this issue, will you please assign this to me?

**Comment by nidhisingh-1** [comment]
I would like to work on this

**Comment by mishraaditya595** [comment]
ScanIt is not accepting these kind of issues for GSSOC.
