### ISSUE TITLE
Documentation of the entire codebase

### ISSUE THREAD

**Issue by mishraaditya595** [mishraaditya595/ScanIt#6]
As one might notice that the codebase for the project has not been documented properly.

**Comment by Vrushti24** [comment]
I would love to work on this issue but can you elaborate what exactly I have to do??

**Comment by mishraaditya595** [comment]
If you go through the code, you will notice that the code has not been documented. So, you have to go through the code, understand what does a function do and document it with the help of comments.

**Comment by Vrushti24** [comment]
Okay I will try to do that u can assign me

**Comment by mishraaditya595** [comment]
ok assigning the issue!

**Comment by Vrushti24** [comment]
Thank u for this how much time is allocated to me to complete?

**Comment by mishraaditya595** [comment]
I think 48 hours will be sufficient for documenting it.

**Comment by Vrushti24** [comment]
Okay👍

**Comment by Vrushti24** [comment]
Sir I m finding difficulty in understanding the code because I have  very
little knowledge of java or kotlin is there someway still I can do
documentation ??
I m sorry to trouble you

**Comment by RuchiGitHu** [comment]
> As one might notice that the codebase for the project has not been documented properly.

Good Evening... 
Can you please send me the link of github repo for this issue? So that I can check if I am able to resolve this issue.....
Thanks in advance...

**Comment by mishraaditya595** [comment]
Check the repo in whose **issue's section** you have commented.

**Comment by RuchiGitHu** [comment]
Thanks..

**Comment by deepthiteki** [comment]
Hey @mishraaditya595 
Can I work on this issue under GSSOC'21

**Comment by coderdada6** [comment]
I want to work on this issue , being a participant at GSSoC'21 can i work on it?

**Comment by mohdjameel2412** [comment]
please assign it to me under gssoc21

**Comment by mishraaditya595** [comment]
Hello everyone, glad to see your interest in ScanIt, as there are multiple interested developers, I will try to give chance to everyone on a first-come-first-serve basis. @deepthiteki  had approached first so he will be getting the chance. If he does not respond in the next 24 hours, the next in line will be assigned.

**Comment by coderdada6** [comment]
sure sir.

**Comment by deepthiteki** [comment]
Thank you, sir
I will try to create pr as soon as possible

**Comment by shreyadubey0902** [comment]
Hey, I am a participant at GSSoc'21 , I am really interested to contribute to this issue can you assign me?

**Comment by mishraaditya595** [comment]
Hey @deepthiteki, did you unassign yourself or was it a mistake?

**Comment by deepthiteki** [comment]
Hi @mishraaditya595,
I don't have much experience in kotlin so It's taking much longer than I thought and there seems to be a lot of people who are interested and have related skill set.
That's why I unassigned myself.
Sorry

**Comment by mishraaditya595** [comment]
Hey @shreyadubey0902, you can start working on it. Keep me informed!

**Comment by shreyadubey0902** [comment]
> Hey @shreyadubey0902, you can start working on it. Keep me informed!

thankyou @mishraaditya595 Ok I will keep informing it

**Comment by amritakesh** [comment]
hello
i'm taking part in gssoc 2021. And i would like work on this issue, will you please assign this to me?

**Comment by mishraaditya595** [comment]
Hey @shreyadubey0902, It has been 5 days since you have been assigned with this issue and you have not forked the repo yet. Can I know the status?

**Comment by simonnepinto** [comment]
Can I work on this issue?

**Comment by mishraaditya595** [comment]
Hey @simonnepinto, sorry for the delayed response. You can start working.

**Comment by simonnepinto** [comment]
Thanks @mishraaditya595!
For documenting the codebase, I need to add comments (explaining what every function does) in every Kotlin file, right?

**Comment by mishraaditya595** [comment]
yes

**Comment by simonnepinto** [comment]
Yeah, I will. Thank you.

**Comment by mhammadsaani** [comment]
Is this project still active?

**Comment by sarahBenzaquen** [comment]
Hi , I'm trying to run the project on my xiaomi but I have errors like "Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve ai.artivatic:cameracontroller:2.0.1."
I'm new on Android , someone could help me please ?

**Comment by mishraaditya595** [comment]
Hi @sarahBenzaquen,
Thanks for showing interest in the project. I am not actively maintaining this project anymore. Hence, there might be some issues with the changes in the Android OS framework and the deprecation of APIs. Feel free to fork the project and make your desired changes.
