### ISSUE TITLE
Problem with OCRFragment.kt file

### ISSUE THREAD

**Issue by leoshrey** [mishraaditya595/ScanIt#60]
**Description**

I downloaded google-services.json after creating a Firebase project, also I updated the build.gradle files in app and project directories ( included code to dependencies as mentioned on the firebase console ). But I am facing an issue with building the application as it is throwing errors on various lines of OCRFragment.kt file. Which I think is the problem with firebase ML kit.
Looking for someone who successfully completed building or faced the same issue.

**Working Environment**

Operating System : MAC OS 
IDE : Android Studio

**Screenshots**

Attaching the screenshot of output log.
 
![image](https://user-images.githubusercontent.com/53581274/111684291-8a0e0a00-884c-11eb-9afc-40c732a6dfa3.png)

**Comment by mishraaditya595** [comment]
hey, I guess wherever you are getting the error regarding the context part, replace "context" with "requireContext".
Coming to the problem with visionTextDetector, make sure your dependencies in the build.gradle (app) file have these two: 
`implementation 'com.google.firebase:firebase-core:15.0.2'
    implementation 'com.google.firebase:firebase-ml-vision:15.0.0'`

And for the rest, I guess updating the Kotlin plugin in Android Studio will do the job.

**Comment by av-arvind77** [comment]
@leoshrey Try with this firebase ML vision dependency:

implementation 'com.google.firebase:firebase-ml-vision:24.1.0'

Also, in place of visionTextDetector, replace it with :
val detector = FirebaseVision.getInstance()
        .onDeviceTextRecognizer

Change visionTextDetector to this line.

For any further assistance: https://firebase.google.com/docs/ml-kit/android/recognize-text
Check this one.

**Comment by rahulsain** [comment]
@leoshrey Remove these dependencies from your app build.gradle file
`implementation platform('com.google.firebase:firebase-bom:26.7.0')`
`implementation 'com.google.firebase:firebase-analytics-ktx'`
and insert
`implementation 'com.google.firebase:firebase-core:15.0.2'`
`implementation 'com.google.firebase:firebase-ml-vision:15.0.0'`

**Comment by leoshrey** [comment]
> @leoshrey Remove these dependencies from your app build.gradle file
> `implementation platform('com.google.firebase:firebase-bom:26.7.0')`
> `implementation 'com.google.firebase:firebase-analytics-ktx'`
> and insert
> `implementation 'com.google.firebase:firebase-core:15.0.2'`
> `implementation 'com.google.firebase:firebase-ml-vision:15.0.0'`

@rahulsain, Thanks a lot, it helped me out. 
Now the application is building successfully.

**Comment by rahulsain** [comment]
> > @leoshrey Remove these dependencies from your app build.gradle file
> > `implementation platform('com.google.firebase:firebase-bom:26.7.0')`
> > `implementation 'com.google.firebase:firebase-analytics-ktx'`
> > and insert
> > `implementation 'com.google.firebase:firebase-core:15.0.2'`
> > `implementation 'com.google.firebase:firebase-ml-vision:15.0.0'`
> 
> @rahulsain, Thanks a lot, it helped me out.
> Now the application is building successfully.

Can you close the issue if solved?
Thank you in advance

**Comment by leoshrey** [comment]
Sure, closing now
