### ISSUE TITLE
App Crashing while opening Camera, some part is not working correctly

### ISSUE THREAD

**Issue by rahulsain** [mishraaditya595/ScanIt#62]
**Description**

Some Features are not working in the application. Like scanning image , no preview mode , error while validating and app crash.

**Stack**

Project stack or language (eg. Frontend):

Logical Implementation

**Working Environment**

Operating System (eg Linux): Win 10

Browser (eg. Chrome): Edge

Device (eg. Laptop or Phone): Laptop/Phone 

**Screenshots**

![image](https://user-images.githubusercontent.com/50570677/111988314-5b3ab100-8b36-11eb-864d-a678c8e018a2.png)
![image](https://user-images.githubusercontent.com/50570677/111988337-6392ec00-8b36-11eb-8924-be3264ad17e2.png)

**Comment by av-arvind77** [comment]
@rahulsain Hello Rahul, I was facing the same problem when I installed the app.
I am working on this issue to get it fixed asap. Once @mishraaditya595 merge it will start working.

**Comment by rahulsain** [comment]
@av-arvind77 But none of us assigned yet. Wait for @mishraaditya595 permission

**Comment by mishraaditya595** [comment]
Hey @rahulsain, you can proceed to work on it.

**Comment by av-arvind77** [comment]
@mishraaditya595 Assign this task to me also. As I have worked on this issue and also implemented my logic for camera part. and also created PR for that.

**Comment by mishraaditya595** [comment]
I just saw that. Sounds good to me.
