### ISSUE TITLE
Auto Labelling Hack

### ISSUE THREAD

**Issue by aishux** [mishraaditya595/ScanIt#66]
**Description**

Add GitHub action to auto label issues with gssoc21 label when contributor asks to work under gssoc21. As it takes time for the maintainer to add labels, I can add a script that can auto-label issues with the GSSOC21 label whenever contributors ask to work under that label.

**Stack**

Project stack or language (eg. Frontend): YAML language 

**Working Environment**

Operating System (eg Linux): MacOS

Browser (eg. Chrome): Chrome

Device (eg. Laptop or Phone): Laptop 

**Screenshots**

Please add a screenshot if applicable

[Optional] **Additional Context**

I want to be assigned this issue with a GSSOC tag and a level tag.

**Comment by aishux** [comment]
Please assign me this issue with a GSSOC tag

**Comment by mishraaditya595** [comment]
Hey, apologies for the delay. I issue you mentioned here does not seem to be adding much value to the project. There are a lot of active issues which you can pick up that needs urgent attention. Thanks for your interest.
