### ISSUE TITLE
I want to add the tech stack section with logos 

### ISSUE THREAD

**Issue by srisatya1197** [mishraaditya595/ScanIt#67]
I want to add tech stack used in this read me file .I want to work on this issue . I'm a participant of GSSOC'21 please assign me this issue @mishraaditya595 .

**Comment by mishraaditya595** [comment]
Hello @srisatya1197, apologies for the delay. The issue you mentioned here does not seem to be adding much value to the project. There are a lot of active issues which you can pick up that needs urgent attention. Thanks for your interest.
