### ISSUE TITLE
The app can't save any PDF file. A 'SS Error' toast pops up every time I try to save a file.

### ISSUE THREAD

**Issue by deepsjuneja** [mishraaditya595/ScanIt#69]
**Description**

The app can't save any PDF file. A 'SS Error' toast pops up every time I try to save a file.

**Stack**

Project stack or language (eg. Frontend): Android

**Working Environment**

Operating System (eg Linux): Windows

Browser (eg. Chrome): Chrome

Device (eg. Laptop or Phone): Phone

**Screenshots**

Please add a screenshot if applicable
![Screenshot_20210422_192303](https://user-images.githubusercontent.com/52399007/115726430-59b41100-a3a0-11eb-9507-af38f0af98f3.jpg)

[Optional] **Additional Context**

**Comment by mishraaditya595** [comment]
Since the launch of Android 11, Google has made it compulsory for apps to use scoped storage. Since the app is not using scoped storage yet, you are experiencing this error. The file is not getting saved in the storage of the phone. I have also raised an issue for the same #64.

**Comment by deepsjuneja** [comment]
> Since the launch of Android 11, Google has made it compulsory for apps to use scoped storage. Since the app is not using scoped storage yet, you are experiencing this error. The file is not getting saved in the storage of the phone. I have also raised an issue for the same #64.

Okay! Will try to look into it, and will inform you if I am able solve it.

**Comment by mishraaditya595** [comment]
That's really great. Do you want me to assign that issue to you as well?

**Comment by apoorva0107** [comment]
@mishraaditya595 I can take up this issue, but before that can you please elaborate on how to solve this issue?
