### ISSUE TITLE
update contributing.md

### ISSUE THREAD

**Issue by khareyash05** [mishraaditya595/ScanIt#70]
Hi I would like to update contributing.md and add the following with proper steps-
1. Difference between git and github
2. Cloning a Repo
3. Creating a Branch and updating it locally as well as forked time to time
4. Creating a PR
5. Squashing Commits

**Comment by mishraaditya595** [comment]
Hey, thanks for your interest in the project. I think they are self-explanatory and don't really need to be in contributing.md. There are a lot more open issues that you might like to work on.
