### ISSUE TITLE
Improvements to README.md

### ISSUE THREAD

**Issue by mishraaditya595** [mishraaditya595/ScanIt#8]
The readme section of the project is very basic. A lot of improvements can be done.

**Comment by kanishkaa24** [comment]
Hey
Can I work on this?

**Comment by mishraaditya595** [comment]
Sure. I am assigning you the issue.

**Comment by mishraaditya595** [comment]
Hey @kanishkaa24, any updates?

**Comment by kanishkaa24** [comment]
> Hey @kanishkaa24, any updates?

I'll make the PR tomorrow. It's under progress.

**Comment by kanishkaa24** [comment]
Do you have any logo ?

**Comment by mishraaditya595** [comment]
You can find it [here](https://github.com/mishraaditya595/ScanIt/blob/master/app/src/main/scanit_icon-playstore.png)

**Comment by kanishkaa24** [comment]
Can you tell me the procedure to run the code locally ?

**Comment by mishraaditya595** [comment]
You will need Android Studio on your system.

**Comment by kanishkaa24** [comment]
I am planning to add it in the readme section so that the contributors can work accordingly.

**Comment by mishraaditya595** [comment]
Ok, draft it out. I will add my inputs to your work.

**Comment by kanishkaa24** [comment]
I don't have any idea about this. Could you give me some pointers?

**Comment by mishraaditya595** [comment]
Pointers as in?

**Comment by kanishkaa24** [comment]
As in how to install and run code locally
